### PR TITLE
David's Task 3: Adding collection tool 

### PR DESCRIPTION
**Pull request by King-kay**
Added collection tool for Typhoid Fever symptoms Data

### CODE REVIEW

**Comment by Mboalab** [comment]
Hi @King-kay thanks for the forms. We need to think also about offline solution.

**Comment by Mboalab** [comment]
Are you working on task 3 or task 4?

**Comment by King-kay** [comment]
I'll like to contribute to task 3

**Comment by King-kay** [comment]
We could use fied mobile data collection app.. which we can sync the data as soon as in better suited environment.

> Hi @King-kay thanks for the forms. We need to think also about offline solution.

We could use fied mobile data collection app.. which we can sync the data as soon as in better suited environment.

**Pull request merged**
