### PR TITLE
Task 1

### PR DESCRIPTION
**Pull request by EddieMaiyo**
logo
Mboalab Logo 2
Mboalab Logo 1

Either one can be used depending on the background

### CODE REVIEW

**Comment by Mboalab** [comment]
Hello Eddie, Thanks for sending in your contribution. Very great logo design. Well done for highlighting key elements of the project on your design such as the diagnostic side, with the microscope represented. Maybe with a reference to Artificial intelligence and machine learning and a more specific name this already amazing design will reach perfection. Great Job!

**Comment by EddieMaiyo** [comment]
Thank you very much for your response and appreciation 

Sent from Yahoo Mail on Android 
 
  On Sun, Oct 31, 2021 at 14:03, ***@***.***> wrote:   


Merged #112 into outreachy-2022.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by EddieMaiyo** [comment]
You got me thinking yesterevening about the AI on the medical aspect and today I drew on word an example of what would be an App. I don't know your view on this but check it out anyway...

Sent from Yahoo Mail on Android 
 
  On Sun, Oct 31, 2021 at 14:34, eddie ***@***.***> wrote:   Thank you very much for your response and appreciation 

Sent from Yahoo Mail on Android 
 
  On Sun, Oct 31, 2021 at 14:03, ***@***.***> wrote:   


Merged #112 into outreachy-2022.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by EddieMaiyo** [comment]
I am not a professional coder, that's why I used Word

Sent from Yahoo Mail on Android 
 
  On Tue, Nov 2, 2021 at 13:43, eddie ***@***.***> wrote:   You got me thinking yesterevening about the AI on the medical aspect and today I drew on word an example of what would be an App. I don't know your view on this but check it out anyway...

Sent from Yahoo Mail on Android 
 
  On Sun, Oct 31, 2021 at 14:34, eddie ***@***.***> wrote:   Thank you very much for your response and appreciation 

Sent from Yahoo Mail on Android 
 
  On Sun, Oct 31, 2021 at 14:03, ***@***.***> wrote:   


Merged #112 into outreachy-2022.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Pull request merged**
