### PR TITLE
Create Fatimat Oyekanmi

### PR DESCRIPTION
**Pull request by Fatimat-01**

### CODE REVIEW

**Comment by Fatimat-01** [comment]
Task 3- Design a Data collection tool to record symptoms Data.
Google form was designed to collect data about Typhoid fever which is both easy to use and Fast for Data collection and will also make Data Processing quite easy.

**Comment by Fatimat-01** [comment]
Hello @Mboalab . Can you please review my Pull Request on Task 3 and give feedbacks?
https://docs.google.com/forms/d/1NoLg5fWxBDuvrbB0Oln7s5QNQPYQetFIuiLgBkVHr2E/edit

**Comment by Fatimat-01** [comment]
@Mboalab , kindly review my PR

**Comment by Mboalab** [comment]
Hi Fatimat Really appreciate your contribution. But You have to know that it is the association of some particular synptoms that help to determine the level of severity of typhoid.

**Comment by Fatimat-01** [comment]
@Mboalab , Thanks for the merge 
Yes I do know, that's why I put various symptoms there.
So the number of, or various symptoms experienced by the patient will determine the level of severity of the illness.

**Pull request merged**
