### PR TITLE
Design challenge Submission

### PR DESCRIPTION
**Pull request by ChocLawrence**
1. Proposed website designs
2. Proposed Logo design
3. List of proposed features for the platform
4. PDF document outlining all the programming languages and the high level architecture
5. Working prototype of website: [Protoype](https://github.com/ChocLawrence/mboalab-africa)

Reviewers/Mentors
-------------------
@agossoubido2021 
@NodiraIbrogimova  / @nodira.ibrogimova@gmail.com
@jafsiaelisee@gmail.com

### CODE REVIEW

**Comment by jafsia** [comment]
good

**Comment by agossoubido2021** [comment]
Good
I suggest for Mentors/Reviewers,  please include ''@NodiraIbrogimova" / nodira.ibrogimova@gmail.com

Also could you kindly upload the working prototype on a free Host or github.io and provide us With the link in  so that we Can Access your prototype online?
Thanks

**Comment by agossoubido2021** [comment]
Sorry Lawrence, I have already Seen the github.io link for your working prototype.
Just include ''nodira.ibrogimova@gmail.com/@NodiraIbrogimova    in the list of Reviewers
Thanks.

**Comment by ChocLawrence** [comment]
My bad sirs. I have updated the reviewers list to include @NodiraIbrogimova

**Comment by NodiraIbrogimova** [comment]
@ChocLawrence, thanks for taking your time and delivering this contribution.
You have an impressive portfolio. The proposal clarifies many details regarding the process and your experience in web development.
If you can provide your design in Figma, please ping us.

**Comment by ChocLawrence** [comment]
@NodiraIbrogimova  thanks.I have just the same design pictures I previewed in the md file as jpg, and not Figma files.

**Pull request merged**
