### PR TITLE
Task2

### PR DESCRIPTION
**Pull request by Jessie-Djuatio**
I built a website using bootstrap 4, CSS,  javascript and hosted it on Cpanel. You can access the site with the following link: [](https://mboalab.lesenteurbon.com/)
[https://mboalab.lesenteurbon.com/](url)
I'm waiting for your review. Thanks!

Mboalab

### CODE REVIEW

**Comment by Jessie-Djuatio** [comment]
#33 Link to my site: [Here](https://mboalab.lesenteurbon.com/)

**Comment by Mboalab** [comment]
Hi jessica. Really appreciate your devotion building this website. I think you should have also included contents about the Outreachy Internship program. Good Job. I'm impressed.

**Comment by Mboalab** [comment]
You need to add some info about outreachy basically who they are and what they do.

**Comment by Jessie-Djuatio** [comment]
Hello, Thanks for your review. I am currently working on the outreachy content as part of my task 4 as well as the data collection part. Hopefully, by this evening, I'll be done.
Thanks.

**Pull request merged**
